# Generated by Django 3.2 on 2022-11-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('mobile', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('category', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('valuation', models.CharField(max_length=122)),
                ('companyname', models.CharField(max_length=122)),
                ('country', models.CharField(choices=[('ind', 'India'), ('ch', 'China'), ('uk', 'U.K.')], default='Ind', max_length=20)),
                ('file', models.ImageField(default='profile_pic/default.jpg', null=True, upload_to='profile_pic/')),
                ('message', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
