# Generated by Django 3.2 on 2022-11-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='category',
            field=models.CharField(choices=[('ent', 'Entrepreneur'), ('inv', 'Investor')], default='ent', max_length=20),
        ),
    ]
